### ISSUE TITLE
输入法vm错位问题

### ISSUE THREAD

**Issue by lilengqiang** [VincentWei/mg-demos#1]
选择单个字后，vm框提示字位置会有交叉的现象，您那有解决办法吗？
![image](https://user-images.githubusercontent.com/52372001/63211334-56c34080-c128-11e9-8a82-22e4897b2dfa.png)
通过如下函数获取的位置会出现交叉现象
![image](https://user-images.githubusercontent.com/52372001/63211374-c1747c00-c128-11e9-8623-0f41a2ded120.png)

**Comment by VincentWei** [comment]
The code is licensed under Apache 2.0, you can try to resolve this bug by yourself.

Tip: the code calculates the extent of the words by using a DC returned by GetDC, however, it does not ensure the LOGFONT object is the right one.
